name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ubuntu-latest-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Check formatting (cargo fmt)
        run: cargo fmt -- --check

      - name: Run clippy (deny warnings)
        run: cargo clippy -- -D warnings

      - name: Run tests
        run: cargo test --verbose

  docs:
    name: Build and publish docs
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          override: true

      - name: Build docs
        run: cargo doc --no-deps

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./target/doc

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with: {}
